include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  exclude:
    - build/**
    - ml/**
    - android/**

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_print
    - cancel_subscriptions
    - close_sinks
    - prefer_final_fields
    - prefer_single_quotes
    - test_types_in_equals
    - unawaited_futures
    - use_super_parameters
